version: '3.4'

services:
  restaurant:
    image: restaurant
    build:
      context: restaurant
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
